apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: jaiglvolu-go 
  janus-idp.io/tekton: jaiglvolu-go
  backstage.io/kubernetes-id: jaiglvolu-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jaiglvolu-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  